[package]
name = "rl-algorithms"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "3.0.0"
env_logger = "0.11.7"
log = "0.4.26"
maplit = "1.0.2"
rand = "0.9.0"
strum = "0.27.1"
strum_macros = "0.27.1"
